// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGe7lfcY_YqgXjlqCmR8114_r-jfH7qHU',
    appId: '1:328960575275:web:4d9df1913a0d2084e1276e',
    messagingSenderId: '328960575275',
    projectId: 'doctor-app-bd0db',
    authDomain: 'doctor-app-bd0db.firebaseapp.com',
    storageBucket: 'doctor-app-bd0db.firebasestorage.app',
    measurementId: 'G-TFJF6558K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqoshSBzuLDh_nC0JFs505Uh-wd1Eymk',
    appId: '1:328960575275:android:7961263b96337f97e1276e',
    messagingSenderId: '328960575275',
    projectId: 'doctor-app-bd0db',
    storageBucket: 'doctor-app-bd0db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuH7dz_WCsaBtGs3Nm9ap5FWlddM5Mnmg',
    appId: '1:328960575275:ios:075d6061e21e286ae1276e',
    messagingSenderId: '328960575275',
    projectId: 'doctor-app-bd0db',
    storageBucket: 'doctor-app-bd0db.firebasestorage.app',
    iosBundleId: 'com.example.doctorApp',
  );
}
